# Generated by Django 2.2.2 on 2019-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apis',
            name='apimethod',
            field=models.CharField(choices=[('delete', 'delete'), ('patch', 'patch'), ('get', 'get'), ('post', 'post'), ('put', 'put')], default='get', max_length=200, null=True, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apimethod',
            field=models.CharField(choices=[('delete', 'delete'), ('patch', 'patch'), ('get', 'get'), ('post', 'post'), ('put', 'put')], default='get', max_length=200, null=True, verbose_name='请求方法'),
        ),
    ]
