# Generated by Django 2.2.2 on 2019-07-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
